# Generated by Django 4.2.7 on 2025-12-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_failed_due_to_violation',
            field=models.BooleanField(default=False, help_text='Failed due to tab switching violation'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='tab_switch_warnings',
            field=models.IntegerField(default=0, help_text='Number of tab switch warnings'),
        ),
    ]
