# Generated by Copilot: Add 'both' to lesson_type and make order auto-managed
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_course_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(max_length=10, choices=[('video', 'Video'), ('pdf', 'PDF'), ('both', 'Both')]),
        ),
    ]
